[versions]
neoforge = "21.1.122"
mdg = "2.0.78"
neoforgeRange = { require = "[21.1.122,)", prefer = "21.1.122" }
neoform = "1.21-20240613.152323"

[libraries.testframework]
module = "net.neoforged:testframework"
version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
